spring:
  application:
    name: credito-api
  datasource:
    url: jdbc:postgresql://localhost:5432/credito-constituido
    username: credito
    password: credito
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always
  kafka:
    # Comma-delimited list of host:port pairs for all Kafka components
    bootstrap-servers: "localhost:9092"
    producer:
      # Serializer class for keys and values
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JacksonJsonSerializer"
server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:mysecretkey}